source('Rcode/_supporting_scripts/report_output_config.R')
info <- jsonlite::fromJSON('Info/Nigeria_general_info.json')
stopifnot('Under National Administration' %in% info$georepo_boundary_exclusions$name)
ids <- report_excluded_admin_ids(getwd(), 'Nigeria', 1L)
stopifnot(identical(ids, 'admin1_36'))
e <- new.env()
load('Data/shapeFiles/georepo_NGA_shp/Nigeria_Amat_Names.rda', envir = e)
kept <- filter_report_admin_rows(e$admin1.names, ids, 'Internal')
stopifnot(nrow(kept) == 37L, 'Federal Capital Territory' %in% kept$GeoRepo)
input <- data.frame(region = c('admin1_1', 'admin1_36', 'admin1_38'), median = c(10, 99, 20))
stopifnot(identical(filter_report_admin_rows(input, ids), input[c(1, 3), ]))
stopifnot(identical(filter_report_admin_rows(input, character()), input))
stopifnot(identical(input$median, c(10, 99, 20)))
cat('Nigeria report exclusion tests passed: 37 areas, stable IDs and estimates.\n')
